# Generated by Django 4.1 on 2022-09-07 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Status', models.CharField(default='PENDING', max_length=50, null=True)),
                ('TotalIterations', models.IntegerField()),
            ],
        ),
    ]
